name: Build
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y g++-11 g++-12 clang-14 clang-15
      - name: Run Build Matrix
        run: |
          COMPILERS="g++-11 g++-12 clang++-14 clang++-15" \
          STANDARDS="c++14 c++17 c++20" \
          MODES="Debug Release" \
          .github/scripts/build-matrix.sh

  ubuntu-jammy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y g++-9 g++-10 clang-11 clang-12 clang-13 clang-14 clang-15
      - name: Run Build Matrix
        run: |
          COMPILERS="g++-9 g++-10 clang++-11 clang++-12 clang++-13 clang++-14 clang++-15" \
          STANDARDS="c++14 c++17 c++20" \
          MODES="Debug Release" \
          .github/scripts/build-matrix.sh

  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Run Build Matrix
        run: |
          COMPILERS="c++ g++-13 g++-14" \
          STANDARDS="c++14 c++17 c++20" \
          MODES="Debug Release" \
          .github/scripts/build-matrix.sh

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Run Build Matrix
        shell: pwsh
        run: |
          bash .github/scripts/build-matrix.sh