name: CppCheck

on: [push]

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install cppcheck

    - name: Run CppCheck
      working-directory: ${{runner.workspace}}/Atomic
      shell: bash
      run: find ./include -name '*.hpp' | xargs cppcheck --enable=all -q --force -Iinclude/

  ubuntu-bionic:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: sudo apt-get install cppcheck

    - name: Run CppCheck
      working-directory: ${{runner.workspace}}/Atomic
      shell: bash
      run: find ./include -name '*.hpp' | xargs cppcheck --enable=all -q --force -Iinclude/

  macos-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install cppcheck

    - name: Run CppCheck
      working-directory: ${{runner.workspace}}/Atomic
      shell: bash
      run: find ./include -name '*.hpp' | xargs cppcheck --enable=all -q --force -Iinclude/

  windows-2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: choco install cppcheck -y

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}\build

    - name: Build
      shell: bash 
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Debug
      
    - name: Run CppCheck
      working-directory: ${{runner.workspace}}/build
      run: ls -la

  windows-2016:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: choco install cppcheck -y