name: Documentation

on: 
  push: 
      branches:
        - stable
        - dev 

jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code      
        uses: actions/checkout@v2

      - name: Generate Documentation
        working-directory: ${{runner.workspace}}/Atomic
        shell: bash
        run: sudo chmod +x ./tools/build_documentation.sh; ./tools/build_documentation.sh

      - uses: actions/upload-artifact@v2
        with:
            name: Upload Documentation
            path: ${{runner.workspace}}/Atomic/docs/