name: Linux

on: [push]

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ g++-13, g++-14, clang++-14, clang++-15 ]
        standard: [ c++14, c++17, c++20, c++23 ]
        mode: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install g++-13 g++-14 clang-14 clang-15

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/Atomic/build

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/Atomic/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_FLAGS=-std=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler}}; cmake --build . --config ${{ matrix.mode }}

      - name: Run Tests
        working-directory: ${{runner.workspace}}/Atomic/build
        shell: bash
        run: ./Tests
  
  ubuntu-focal:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
            compiler: [ g++-9, g++-10, clang++-9, clang++-10 ]
            standard: [ c++14, c++17, c++2a ]
            mode: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get install g++-9 g++-10 clang-9 clang-10

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/Atomic/build

    - name: Build 
      shell: bash
      working-directory: ${{runner.workspace}}/Atomic/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_FLAGS=-std=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler}}; cmake --build . --config ${{ matrix.mode }} 
      
    - name: Run Tests
      working-directory: ${{runner.workspace}}/Atomic/build
      shell: bash
      run: ./Tests 