name: Macintosh

on: [push]

jobs:
  macos-latest:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ c++, g++ ]
        standard: [ c++14, c++17, c++2a ]
        mode: [ Debug, Release, RelWithDebInfo, MinSizeRel ]
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install cppcheck; ln -s "$(brew --prefix llvm)/share/clang/run-clang-tidy.py" "/usr/local/bin/run-clang-tidy.py"

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/Atomic/build

    - name: Build 
      shell: bash
      working-directory: ${{runner.workspace}}/Atomic/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_FLAGS=-std=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler}}; cmake --build . --config ${{ matrix.mode }}
  
    - name: Run CppCheck
      working-directory: ${{runner.workspace}}/Atomic
      shell: bash
      run: find ./include -name '*.hpp' | xargs cppcheck --enable=all -q --force -Iinclude/

    - name: Run Clang-Tidy
      working-directory: ${{runner.workspace}}/Atomic
      shell: bash 
      run: $(brew --prefix llvm)/share/clang/run-clang-tidy.py -header-filter='.*' -p build/ -quiet

    - name: Run Tests
      working-directory: ${{runner.workspace}}/Atomic/build
      shell: bash
      run: ./Tests