name: Macintosh

on: [push]

jobs:
  macos-latest:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ c++, g++ ]
        standard: [ c++14, c++17, c++2a ]
        mode: [ Debug, Release, RelWithDebInfo, MinSizeRel ]
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: brew install cmake cppcheck llvm

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Build 
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_FLAGS=-std=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler}}; cmake --build . --config ${{ matrix.mode }}
  
    - name: Run CppCheck
      working-directory: ${{runner.workspace}}/Atomic
      shell: bash
      run: cppcheck --enable=all -q --force include/**/**/*.hpp -Iinclude/

    - name: Run Clang-Tidy
      working-directory: ${{runner.workspace}}/Atomic/include
      shell: bash 
      run: find -name '*.hpp' | xargs /usr/bin/clang-tidy 

    - name: Run Tests
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ${{runner.workspace}}/build/Tests