name: Windows

on: [push]

jobs:
  windows:
    strategy:
      matrix:
        compiler: [ clang, gcc, msvc-14.0, msvc-14.2 ]
        standard: [ c++14, c++17, c++20, c++23 ]
        mode: [ Debug, Release ]
        os: [windows-latest, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}\build

    - name: Build
      shell: bash 
      working-directory: ${{runner.workspace}}\build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_FLAGS=-std=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler}}; cmake --build . --config ${{ matrix.mode }}
      
    - name: Run Tests
      working-directory: ${{runner.workspace}}\build\${{ matrix.mode }}
      run: ./Tests.exe