name: Windows

on: [push]

jobs:
  windows-2019:
    runs-on: windows-2019
    strategy:
      matrix:
        compiler: [ clang, gcc, msvc-14.0, msvc-14.2 ]
        standard: [ c++14, c++17, c++2a ]
        mode: [ Debug, Release, RelWithDebInfo, MinSizeRel ]
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: choco install cppcheck -y

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}\build

    - name: Build
      shell: bash 
      working-directory: ${{runner.workspace}}\build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_FLAGS=-std=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler}}; cmake --build . --config ${{ matrix.mode }}
      
    - name: Run Tests
      working-directory: ${{runner.workspace}}\build\${{ matrix.mode }}
      run: ./Tests.exe

  windows-2016:
    runs-on: windows-2016
    strategy:
      matrix:
        compiler: [ clang, gcc, msvc-14.0, msvc-14.2 ]
        standard: [ c++14, c++17, c++2a ]
        mode: [ Debug, Release, RelWithDebInfo, MinSizeRel ]
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: choco install cppcheck -y

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}\build

    - name: Build
      shell: bash 
      working-directory: ${{runner.workspace}}\build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_CXX_FLAGS=-std=${{ matrix.standard }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler}}; cmake --build . --config ${{ matrix.mode }}
      
    - name: Run Tests
      working-directory: ${{runner.workspace}}\build\${{ matrix.mode }}
      run: ./Tests.exe